name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
    - master
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
 
    steps:
    - name: Update git
      run: |
        apt-get update
        apt-get install -y git
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Install dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get install -y git python3 python3-pip
        python3 -m pip install -r docs/requirements.txt
 
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 docs/deploy.py
